In [1]:
%config Completer.use_jedi = False
import pandas as pd

In [5]:
pew = pd.read_csv('data/pew.csv')

In [6]:
pew.head()

,religion,<$10k,$10-20k,$20-30k,$30-40k,$40-50k,$50-75k,$75-100k,$100-150k,>150k,Don't know/refused
0,Agnostic,27,34,60,81,76,137,122,109,84,96
1,Atheist,12,27,37,52,35,70,73,59,74,76
2,Buddhist,27,21,30,34,33,58,62,39,53,54
3,Catholic,418,617,732,670,638,1116,949,792,633,1489
4,Don’t know/refused,15,14,15,11,10,35,21,17,18,116

In [7]:
#this is how you melt the column you dont want to exist, id_vars is the argument for stating the column you dont want to touch/included
#and there is also a parameters called value_vars similar to id_vars but value_vars means to excluding that values in melting function process
pew_long1 = pd.melt(pew, id_vars='religion')

In [10]:
pew_long1.head(40)

                   religion variable  value
0                  Agnostic    <$10k     27
1                   Atheist    <$10k     12
2                  Buddhist    <$10k     27
3                  Catholic    <$10k    418
4        Don’t know/refused    <$10k     15
5          Evangelical Prot    <$10k    575
6                     Hindu    <$10k      1
7   Historically Black Prot    <$10k    228
8         Jehovah's Witness    <$10k     20
9                    Jewish    <$10k     19
10            Mainline Prot    <$10k    289
11                   Mormon    <$10k     29
12                   Muslim    <$10k      6
13                 Orthodox    <$10k     13
14          Other Christian    <$10k      9
15             Other Faiths    <$10k     20
16    Other World Religions    <$10k      5
17             Unaffiliated    <$10k    217
18                 Agnostic  $10-20k     34
19                  Atheist  $10-20k     27
20                 Buddhist  $10-20k     21
21                 Catholic  $10-20k    617
22       Don’t know/refused  $10-20k     14
23         Evangelical Prot  $10-20k    869
24                    Hindu  $10-20k      9
25  Historically Black Prot  $10-20k    244
26        Jehovah's Witness  $10-20k     27
27                   Jewish  $10-20k     19
28            Mainline Prot  $10-20k    495
29                   Mormon  $10-20k     40
30                   Muslim  $10-20k      7
31                 Orthodox  $10-20k     17
32          Other Christian  $10-20k      7
33             Other Faiths  $10-20k     33
34    Other World Religions  $10-20k      2
35             Unaffiliated  $10-20k    299
36                 Agnostic  $20-30k     60
37                  Atheist  $20-30k     37
38                 Buddhist  $20-30k     30
39                 Catholic  $20-30k    732

In [9]:
pew_long1 = pd.melt(pew, id_vars='religion', var_name= 'income', value_name='count')

In [10]:
pew_long1.head()

             religion income  count
0            Agnostic  <$10k     27
1             Atheist  <$10k     12
2            Buddhist  <$10k     27
3            Catholic  <$10k    418
4  Don’t know/refused  <$10k     15

In [12]:
billboard = pd.read_csv('data/billboard.csv')

In [18]:
billboard.columns

Index(['year', 'artist', 'track', 'time', 'date.entered', 'wk1', 'wk2', 'wk3',
       'wk4', 'wk5', 'wk6', 'wk7', 'wk8', 'wk9', 'wk10', 'wk11', 'wk12',
       'wk13', 'wk14', 'wk15', 'wk16', 'wk17', 'wk18', 'wk19', 'wk20', 'wk21',
       'wk22', 'wk23', 'wk24', 'wk25', 'wk26', 'wk27', 'wk28', 'wk29', 'wk30',
       'wk31', 'wk32', 'wk33', 'wk34', 'wk35', 'wk36', 'wk37', 'wk38', 'wk39',
       'wk40', 'wk41', 'wk42', 'wk43', 'wk44', 'wk45', 'wk46', 'wk47', 'wk48',
       'wk49', 'wk50', 'wk51', 'wk52', 'wk53', 'wk54', 'wk55', 'wk56', 'wk57',
       'wk58', 'wk59', 'wk60', 'wk61', 'wk62', 'wk63', 'wk64', 'wk65', 'wk66',
       'wk67', 'wk68', 'wk69', 'wk70', 'wk71', 'wk72', 'wk73', 'wk74', 'wk75',
       'wk76'],
      dtype='object')

In [26]:
billboard_melt = pd.melt(billboard, id_vars=['year','artist','track','time','date.entered'], var_name='Week', value_name='Rating')

In [27]:
billboard_melt

,year,artist,track,time,date.entered,Week,Rating
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk1,87.0
1,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk1,91.0
2,2000,3 Doors Down,Kryptonite,3:53,2000-04-08,wk1,81.0
3,2000,3 Doors Down,Loser,4:24,2000-10-21,wk1,76.0
4,2000,504 Boyz,Wobble Wobble,3:35,2000-04-15,wk1,57.0
...,...,...,...,...,...,...,...
24087,2000,Yankee Grey,Another Nine Minutes,3:10,2000-04-29,wk76,NaN
24088,2000,"Yearwood, Trisha",Real Live Woman,3:55,2000-04-01,wk76,NaN
24089,2000,Ying Yang Twins,Whistle While You Tw...,4:19,2000-03-18,wk76,NaN
24090,2000,Zombie Nation,Kernkraft 400,3:30,2000-09-02,wk76,NaN
24091,2000,matchbox twenty,Bent,4:12,2000-04-29,wk76,NaN

In [28]:
billboard_melt.shape

(24092, 7)

In [29]:
ebola = pd.read_csv('data/country_timeseries.csv')

In [30]:
ebola.head()

,Date,Day,Cases_Guinea,Cases_Liberia,Cases_SierraLeone,Cases_Nigeria,Cases_Senegal,Cases_UnitedStates,Cases_Spain,Cases_Mali,Deaths_Guinea,Deaths_Liberia,Deaths_SierraLeone,Deaths_Nigeria,Deaths_Senegal,Deaths_UnitedStates,Deaths_Spain,Deaths_Mali
0,1/5/2015,289,2776.0,NaN,10030.0,NaN,NaN,NaN,NaN,NaN,1786.0,NaN,2977.0,NaN,NaN,NaN,NaN,NaN
1,1/4/2015,288,2775.0,NaN,9780.0,NaN,NaN,NaN,NaN,NaN,1781.0,NaN,2943.0,NaN,NaN,NaN,NaN,NaN
2,1/3/2015,287,2769.0,8166.0,9722.0,NaN,NaN,NaN,NaN,NaN,1767.0,3496.0,2915.0,NaN,NaN,NaN,NaN,NaN
3,1/2/2015,286,NaN,8157.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3496.0,NaN,NaN,NaN,NaN,NaN,NaN
4,12/31/2014,284,2730.0,8115.0,9633.0,NaN,NaN,NaN,NaN,NaN,1739.0,3471.0,2827.0,NaN,NaN,NaN,NaN,NaN

In [31]:
ebola_long = pd.melt(ebola, id_vars=['Date','Day'])

In [32]:
ebola_long.head()

         Date  Day      variable   value
0    1/5/2015  289  Cases_Guinea  2776.0
1    1/4/2015  288  Cases_Guinea  2775.0
2    1/3/2015  287  Cases_Guinea  2769.0
3    1/2/2015  286  Cases_Guinea     NaN
4  12/31/2014  284  Cases_Guinea  2730.0

In [33]:
#how to split the two-bits information in variable column, by separate the values by the underscore into part to the left: cases and death then part to the right : country variable

#'Cases_Guinea'.split('_')

['Cases', 'Guinea']

In [34]:
variable_split = ebola_long['variable'].str.split('_')

In [35]:
variable_split

0       [Cases, Guinea]
1       [Cases, Guinea]
2       [Cases, Guinea]
3       [Cases, Guinea]
4       [Cases, Guinea]
             ...
1947     [Deaths, Mali]
1948     [Deaths, Mali]
1949     [Deaths, Mali]
1950     [Deaths, Mali]
1951     [Deaths, Mali]
Name: variable, Length: 1952, dtype: object

In [38]:
#telling you its a python list
type(variable_split[0])

list

In [39]:
#series means a single list with index in pandas python, whereas dataframe means a collection more than one series
type(variable_split)

pandas.core.series.Series

In [45]:
variable_split.str.get(0)

0        Cases
1        Cases
2        Cases
3        Cases
4        Cases
         ...
1947    Deaths
1948    Deaths
1949    Deaths
1950    Deaths
1951    Deaths
Name: variable, Length: 1952, dtype: object

In [46]:
variable_split.str.get(1)

0       Guinea
1       Guinea
2       Guinea
3       Guinea
4       Guinea
         ...
1947      Mali
1948      Mali
1949      Mali
1950      Mali
1951      Mali
Name: variable, Length: 1952, dtype: object

In [50]:
# 0 at the end means the first element of Stats_Country and 1 means the second element which is 'Country'
# this is how you do it manually : so when you have a column which stored two bits/kind of information, you can melt them and the do string manipulation to split them up
ebola_long['stats'] = variable_split.str.get(0)
ebola_long['country'] = variable_split.str.get(1)

In [52]:
ebola_long.head(40)

          Date  Day      variable   value  stats country
0     1/5/2015  289  Cases_Guinea  2776.0  Cases  Guinea
1     1/4/2015  288  Cases_Guinea  2775.0  Cases  Guinea
2     1/3/2015  287  Cases_Guinea  2769.0  Cases  Guinea
3     1/2/2015  286  Cases_Guinea     NaN  Cases  Guinea
4   12/31/2014  284  Cases_Guinea  2730.0  Cases  Guinea
5   12/28/2014  281  Cases_Guinea  2706.0  Cases  Guinea
6   12/27/2014  280  Cases_Guinea  2695.0  Cases  Guinea
7   12/24/2014  277  Cases_Guinea  2630.0  Cases  Guinea
8   12/21/2014  273  Cases_Guinea  2597.0  Cases  Guinea
9   12/20/2014  272  Cases_Guinea  2571.0  Cases  Guinea
10  12/18/2014  271  Cases_Guinea     NaN  Cases  Guinea
11  12/14/2014  267  Cases_Guinea  2416.0  Cases  Guinea
12   12/9/2014  262  Cases_Guinea     NaN  Cases  Guinea
13   12/7/2014  260  Cases_Guinea  2292.0  Cases  Guinea
14   12/3/2014  256  Cases_Guinea     NaN  Cases  Guinea
15  11/30/2014  253  Cases_Guinea  2164.0  Cases  Guinea
16  11/28/2014  251  Cases_Guinea     NaN  Cases  Guinea
17  11/23/2014  246  Cases_Guinea  2134.0  Cases  Guinea
18  11/22/2014  245  Cases_Guinea     NaN  Cases  Guinea
19  11/18/2014  241  Cases_Guinea  2047.0  Cases  Guinea
20  11/16/2014  239  Cases_Guinea  1971.0  Cases  Guinea
21  11/15/2014  238  Cases_Guinea     NaN  Cases  Guinea
22  11/11/2014  234  Cases_Guinea  1919.0  Cases  Guinea
23  11/10/2014  233  Cases_Guinea     NaN  Cases  Guinea
24   11/9/2014  232  Cases_Guinea  1878.0  Cases  Guinea
25   11/8/2014  231  Cases_Guinea     NaN  Cases  Guinea
26   11/4/2014  227  Cases_Guinea     NaN  Cases  Guinea
27   11/3/2014  226  Cases_Guinea  1760.0  Cases  Guinea
28   11/2/2014  225  Cases_Guinea  1731.0  Cases  Guinea
29  10/31/2014  222  Cases_Guinea     NaN  Cases  Guinea
30  10/29/2014  220  Cases_Guinea  1667.0  Cases  Guinea
31  10/27/2014  218  Cases_Guinea  1906.0  Cases  Guinea
32  10/25/2014  216  Cases_Guinea     NaN  Cases  Guinea
33  10/22/2014  214  Cases_Guinea     NaN  Cases  Guinea
34  10/21/2014  213  Cases_Guinea  1553.0  Cases  Guinea
35  10/19/2014  211  Cases_Guinea  1540.0  Cases  Guinea
36  10/18/2014  210  Cases_Guinea     NaN  Cases  Guinea
37  10/14/2014  206  Cases_Guinea  1519.0  Cases  Guinea
38  10/13/2014  205  Cases_Guinea     NaN  Cases  Guinea
39  10/12/2014  204  Cases_Guinea  1472.0  Cases  Guinea

In [56]:
#this is how you split the column variables like before more faster
#if you selecting multiple columns remember use double square brackets
ebola_long[['stats_e','country_e']] = (ebola_long['variable']
                                       .str
                                       .split('_', expand=True))

In [57]:
ebola_long

            Date  Day      variable   value   stats country stats_e country_e
0       1/5/2015  289  Cases_Guinea  2776.0   Cases  Guinea   Cases    Guinea
1       1/4/2015  288  Cases_Guinea  2775.0   Cases  Guinea   Cases    Guinea
2       1/3/2015  287  Cases_Guinea  2769.0   Cases  Guinea   Cases    Guinea
3       1/2/2015  286  Cases_Guinea     NaN   Cases  Guinea   Cases    Guinea
4     12/31/2014  284  Cases_Guinea  2730.0   Cases  Guinea   Cases    Guinea
...          ...  ...           ...     ...     ...     ...     ...       ...
1947   3/27/2014    5   Deaths_Mali     NaN  Deaths    Mali  Deaths      Mali
1948   3/26/2014    4   Deaths_Mali     NaN  Deaths    Mali  Deaths      Mali
1949   3/25/2014    3   Deaths_Mali     NaN  Deaths    Mali  Deaths      Mali
1950   3/24/2014    2   Deaths_Mali     NaN  Deaths    Mali  Deaths      Mali
1951   3/22/2014    0   Deaths_Mali     NaN  Deaths    Mali  Deaths      Mali

[1952 rows x 8 columns]

In [68]:
weather = pd.read_csv('data/weather.csv')

In [69]:
#when you see the values of a rows and column is almost the same with many duplicate like tmax and tmin
#it means the data isnt Tidy, they have variable in rows and columns
weather

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,26.4,NaN,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,15.0,NaN,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
#you cant use weather.melt not pd.melt, it call the exact same code as pd, in pivot table you need to use dataframe(name) dot pivot_table not pandas name as pd

weather_melt = weather.melt(
    weather,
    id_vars=['id','year','month','element'],
    var_name='day',
    value_name='temp'
)

TypeError: melt() got multiple values for argument 'id_vars'

In [71]:
weather_melt

          id  year  month element  day  temp
0    MX17004  2010      1    tmax   d1   NaN
1    MX17004  2010      1    tmin   d1   NaN
2    MX17004  2010      2    tmax   d1   NaN
3    MX17004  2010      2    tmin   d1   NaN
4    MX17004  2010      3    tmax   d1   NaN
..       ...   ...    ...     ...  ...   ...
677  MX17004  2010     10    tmin  d31   NaN
678  MX17004  2010     11    tmax  d31   NaN
679  MX17004  2010     11    tmin  d31   NaN
680  MX17004  2010     12    tmax  d31   NaN
681  MX17004  2010     12    tmin  d31   NaN

[682 rows x 6 columns]

In [72]:
#the difference between pivot and pivot_table, for pivot you are assuming there are no duplicate values, for pivot table its the opposite
#index parameters use to specify which column you dont want to move 
#columns parameter use to pivot this element columns it means to look at this element columns for each unique value in this column, its going to create a totally separate column

weather_tidy = weather_melt.pivot_table(
    index=['id','year','month','day'],
    columns='element',
    values='temp'
)

In [74]:
#if you want a regular flat dataframe, sometimes you would have to run reset_index twice
weather_tidy.reset_index()

element       id  year  month  day  tmax  tmin
0        MX17004  2010      1  d30  27.8  14.5
1        MX17004  2010      2  d11  29.7  13.4
2        MX17004  2010      2   d2  27.3  14.4
3        MX17004  2010      2  d23  29.9  10.7
4        MX17004  2010      2   d3  24.1  14.4
5        MX17004  2010      3  d10  34.5  16.8
6        MX17004  2010      3  d16  31.1  17.6
7        MX17004  2010      3   d5  32.1  14.2
8        MX17004  2010      4  d27  36.3  16.7
9        MX17004  2010      5  d27  33.2  18.2
10       MX17004  2010      6  d17  28.0  17.5
11       MX17004  2010      6  d29  30.1  18.0
12       MX17004  2010      7   d3  28.6  17.5
13       MX17004  2010      7  d14  29.9  16.5
14       MX17004  2010      8  d23  26.4  15.0
15       MX17004  2010      8   d5  29.6  15.8
16       MX17004  2010      8  d29  28.0  15.3
17       MX17004  2010      8  d13  29.8  16.5
18       MX17004  2010      8  d25  29.7  15.6
19       MX17004  2010      8  d31  25.4  15.4
20       MX17004  2010      8   d8  29.0  17.3
21       MX17004  2010     10   d5  27.0  14.0
22       MX17004  2010     10  d14  29.5  13.0
23       MX17004  2010     10  d15  28.7  10.5
24       MX17004  2010     10  d28  31.2  15.0
25       MX17004  2010     10   d7  28.1  12.9
26       MX17004  2010     11   d2  31.3  16.3
27       MX17004  2010     11   d5  26.3   7.9
28       MX17004  2010     11  d27  27.7  14.2
29       MX17004  2010     11  d26  28.1  12.1
30       MX17004  2010     11   d4  27.2  12.0
31       MX17004  2010     12   d1  29.9  13.8
32       MX17004  2010     12   d6  27.8  10.5

In [90]:
bb = billboard_melt.loc[(billboard_melt['date.entered']=='2000-02-26') &(billboard_melt['artist']=='2 Pac')]

In [91]:
bb

       year artist                    track  time date.entered  Week  Rating
0      2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   wk1    87.0
317    2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   wk2    82.0
634    2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   wk3    72.0
951    2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   wk4    77.0
1268   2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   wk5    87.0
...     ...    ...                      ...   ...          ...   ...     ...
22507  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk72     NaN
22824  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk73     NaN
23141  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk74     NaN
23458  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk75     NaN
23775  2000  2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26  wk76     NaN

[76 rows x 7 columns]

In [92]:
#how to filtering your dataset with drop duplicate, when you have many duplicate values in a column

billboard_songs = billboard_melt[['year','artist','track','time']]

In [93]:
billboard_songs.head()

   year        artist                    track  time
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22
1  2000       2Ge+her  The Hardest Part Of ...  3:15
2  2000  3 Doors Down               Kryptonite  3:53
3  2000  3 Doors Down                    Loser  4:24
4  2000      504 Boyz            Wobble Wobble  3:35

In [94]:
#this is how you drop the duplicated values
billboard_songs = billboard_songs.drop_duplicates()

In [96]:
billboard_songs

     year            artist                    track  time
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22
1    2000           2Ge+her  The Hardest Part Of ...  3:15
2    2000      3 Doors Down               Kryptonite  3:53
3    2000      3 Doors Down                    Loser  4:24
4    2000          504 Boyz            Wobble Wobble  3:35
..    ...               ...                      ...   ...
312  2000       Yankee Grey     Another Nine Minutes  3:10
313  2000  Yearwood, Trisha          Real Live Woman  3:55
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19
315  2000     Zombie Nation            Kernkraft 400  3:30
316  2000   matchbox twenty                     Bent  4:12

[317 rows x 4 columns]

In [97]:
#how to join the tables, you need a key, so this is how to generate a key
#range is a function in python uses as generator, you give it a number and it'll generate a value, think of it as a list from zero to that number
billboard_songs['id'] = range(len(billboard_songs))

In [98]:
billboard_songs.head()

   year        artist                    track  time  id
0  2000         2 Pac  Baby Don't Cry (Keep...  4:22   0
1  2000       2Ge+her  The Hardest Part Of ...  3:15   1
2  2000  3 Doors Down               Kryptonite  3:53   2
3  2000  3 Doors Down                    Loser  4:24   3
4  2000      504 Boyz            Wobble Wobble  3:35   4

In [99]:
#index=false mean you dont need index column 0,1,2,3,4... in your dataset csv
billboard_songs.to_csv('billboard_songs.csv', index=False)

In [100]:
#combine the songs table and the original one, we combine songs table because we need the id column we just created
#when you press shift+tab, you'll see left will be billboard_melt, right is billboard_songs,how by defualt is inner meaning that only the tables that found matches will be returned back
#if the column names of both left and right df is the same you can say on=None, but if the column names of both sides different you can say left_on,right_on
# we use on here because we have the same column in both sides
billboard_ratings = billboard_melt.merge(
    billboard_songs, on=['year','artist','track','time']

)

In [103]:
billboard_ratings.head(100)

,year,artist,track,time,date.entered,Week,Rating,id
0,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk1,87.0,0
1,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk2,82.0,0
2,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk3,72.0,0
3,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk4,77.0,0
4,2000,2 Pac,Baby Don't Cry (Keep...,4:22,2000-02-26,wk5,87.0,0
...,...,...,...,...,...,...,...,...
95,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk20,NaN,1
96,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk21,NaN,1
97,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk22,NaN,1
98,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk23,NaN,1
99,2000,2Ge+her,The Hardest Part Of ...,3:15,2000-09-02,wk24,NaN,1

In [104]:
billboard_ratings = billboard_ratings[['id','date.entered','Week','Rating']]

In [107]:
billboard_ratings.to_csv('billboard_ratings.csv', index=False)

In [108]:
billboard_ratings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24092 entries, 0 to 24091
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            24092 non-null  int32
 1   date.entered  24092 non-null  object
 2   Week          24092 non-null  object
 3   Rating        5307 non-null   float64
dtypes: float64(1), int32(1), object(2)
memory usage: 847.0+ KB

In [109]:
billboard_songs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 317 entries, 0 to 316
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    317 non-null    int64
 1   artist  317 non-null    object
 2   track   317 non-null    object
 3   time    317 non-null    object
 4   id      317 non-null    int32
dtypes: int32(1), int64(1), object(3)
memory usage: 13.6+ KB

In [110]:
billboard_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24092 entries, 0 to 24091
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          24092 non-null  int64
 1   artist        24092 non-null  object
 2   track         24092 non-null  object
 3   time          24092 non-null  object
 4   date.entered  24092 non-null  object
 5   Week          24092 non-null  object
 6   Rating        5307 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 1.3+ MB

In [ ]:
#tidying data is more for data storange not for to fit it into a model